/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUDS;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto2dosemestre.Conexion;

/**
 *
 * @author Alessandro
 */
public class RENTA extends javax.swing.JFrame {

    /**
     * Creates new form RENTA
     */
    public RENTA() {
        initComponents();
        txtidrenta.setVisible(false);
        cargarSerie();
        cargarcliente();
        cargartipopago();
        cargarusuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrenta = new javax.swing.JTable();
        txtidrenta = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        box1 = new javax.swing.JComboBox<>();
        box2 = new javax.swing.JComboBox<>();
        box3 = new javax.swing.JComboBox<>();
        fprestamo = new javax.swing.JFormattedTextField();
        box4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("RENTA");

        jLabel2.setText("ID_RENTA");

        jLabel3.setText("SERIE");

        jLabel4.setText("ID_CLIENTE");

        jLabel5.setText("ID_USUARIO");

        jLabel6.setText("ID_TIPO_PAGO");

        jLabel7.setText("FECHA_PRESTAMO");

        jLabel9.setText("TOTAL");

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MODIFICAR");

        jButton3.setText("ELIMINAR");

        jButton4.setText("LIMPIAR");

        tblrenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_RENTA", "SERIE", "ID_CLIENTE", "ID_USUARIO", "ID_TIPO_PAGO", "FECHA_PRESTAMO", "FECHA_DEVOLUCION", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblrenta);

        txtidrenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidrentaActionPerformed(evt);
            }
        });

        fprestamo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(fprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtidrenta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(575, 575, 575)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidrenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
        );

        fprestamo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidrentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidrentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidrentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String SERIE = box1.getSelectedItem().toString();
        
        try{
            java.util.Date fPrestamo = new SimpleDateFormat("dd/MM/yyyy").parse(fprestamo.getText());
            //java.util.Date fDevolucion = new SimpleDateFormat("dd/MM/yyyy").parse(fdevolucion.getText());

            java.sql.Date FECHA_PRESTAMO = new java.sql.Date(fPrestamo.getDay(),fPrestamo.getMonth(),fPrestamo.getYear());
            //java.sql.Date FECHA_DEVOLUCION = new java.sql.Date(fDevolucion.getDay(),fDevolucion.getMonth(),fDevolucion.getYear());

            double TOTAL = Double.parseDouble(txttotal.getText());
            
            Connection con = Conexion.getthatConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO RENTA (SERIE,FECHA_PRESTAMO, TOTAL ) VALUES(?, ?, ?)");
            
            // ps.setInt(1, ID_Usuario);
            ps.setString(1, SERIE);
            ps.setDate(2, FECHA_PRESTAMO);
           // ps.setDate(3, FECHA_DEVOLUCION);
            ps.setDouble(3, TOTAL);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Guardado");
             cargarSerie();
        cargarcliente();
        cargartipopago();
           
        } catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.toString());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
 private void cargarSerie(){
     DefaultComboBoxModel modelocaja = (DefaultComboBoxModel) box1.getModel();
    // modelocaja.setSelectedItem(0);

    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd = null;
    int columnas;


    try{
     Connection con = Conexion.getthatConexion();
      ps = con.prepareStatement("SELECT ID_SERIE, DESCRIPCION\n" +
   "  FROM [dbo].[SERIE]");
      rs = ps.executeQuery();
      rsmd = rs.getMetaData();
      columnas = rsmd.getColumnCount();

      while(rs.next()){
          String element = rs.getString(1) + " | " + rs.getString(2) ;
          modelocaja.addElement(element);
         //Object[] fila = new Object[columnas];
         //for(int indice=0; indice<columnas; indice++){
         //fila[indice] = rs.getObject(indice + 1);
         //}
         //modelocaja.addElement(fila);
      }
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.toString());
    }
    }

private void cargarcliente(){

    DefaultComboBoxModel modelocaja = (DefaultComboBoxModel) box2.getModel();
    // modelocaja.setSelectedItem(0);

    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd = null;
    int columnas;


    try{
     Connection con = Conexion.getthatConexion();
      ps = con.prepareStatement("SELECT ID_CLIENTE, CONCAT( [NIT], ' - ', [NOMBRE], ' ', [APELLIDO]) as DESCRIPCION\n" +
   "  FROM [dbo].[CLIENTE]");
      rs = ps.executeQuery();
      rsmd = rs.getMetaData();
      columnas = rsmd.getColumnCount();

      while(rs.next()){
          String element = rs.getString(1) + " | " + rs.getString(2) ;
          modelocaja.addElement(element);
         //Object[] fila = new Object[columnas];
         //for(int indice=0; indice<columnas; indice++){
         //fila[indice] = rs.getObject(indice + 1);
         //}
         //modelocaja.addElement(fila);
      }
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.toString());
    }
 }
      
private void cargartipopago(){
 
 DefaultComboBoxModel modelocaja = (DefaultComboBoxModel) box3.getModel();
    // modelocaja.setSelectedItem(0);

    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd = null;
    int columnas;


    try{
     Connection con = Conexion.getthatConexion();
      ps = con.prepareStatement("SELECT ID_TIPO_PAGO, DESCRIPCION\n" +
   "  FROM [dbo].[TIPO_PAGO]");
      rs = ps.executeQuery();
      rsmd = rs.getMetaData();
      columnas = rsmd.getColumnCount();

      while(rs.next()){
          String element = rs.getString(1) + " | " + rs.getString(2) ;
          modelocaja.addElement(element);
         //Object[] fila = new Object[columnas];
         //for(int indice=0; indice<columnas; indice++){
         //fila[indice] = rs.getObject(indice + 1);
         //}
         //modelocaja.addElement(fila);
      }
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.toString());
    }
 }

private void cargarusuario(){

    DefaultComboBoxModel modelocaja = (DefaultComboBoxModel) box4.getModel();
    // modelocaja.setSelectedItem(0);

    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd = null;
    int columnas;


    try{
     Connection con = Conexion.getthatConexion();
      ps = con.prepareStatement("SELECT ID_USUARIO, CONCAT( [USUARIO], ' - ', [NOMBRE]) as DESCRIPCION\n" +
   "  FROM [dbo].[USUARIO] where [ESTADO] = 1");
      rs = ps.executeQuery();
      // rsmd = rs.getMetaData();
      // columnas = rsmd.getColumnCount();

      while(rs.next()){
          String element = rs.getString(1) + " | " + rs.getString(2) ;
          modelocaja.addElement(element);
         //Object[] fila = new Object[columnas];
         //for(int indice=0; indice<columnas; indice++){
         //fila[indice] = rs.getObject(indice + 1);
         //}
         //modelocaja.addElement(fila);
      }
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.toString());
    }
 }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RENTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box1;
    private javax.swing.JComboBox<String> box2;
    private javax.swing.JComboBox<String> box3;
    private javax.swing.JComboBox<String> box4;
    private javax.swing.JFormattedTextField fprestamo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblrenta;
    private javax.swing.JTextField txtidrenta;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
